### ISSUE TITLE
Intercept `fetch()` call at the sandbox level

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/WebAssemblyStudio#112]
Currently we are writing `fetch(getFileURL('out/main.wasm'))` in the examples. It is preferable if we will use just `fetch('../out/main.wasm')`.

We can use/intercept this function on the "sandboxed" window, and extend request (URLs) with blob URLs.

**Comment by mbebenita** [comment]
👍

**Comment by yurydelendik** [comment]
Fixed by #117
