### ISSUE TITLE
LLVM symbols are missing.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#128]
STR:

1. https://webassembly.studio/?f=18gvrx
2. Click build
3. Open `out/main.wasm` and see that function names are missing.

In `build.ts` we pass "-g -O3" so symbols should appear. I think this is a problem in the service, because the Binary Explorer also doesn't show anything that may look like symbols.

**Comment by mbebenita** [comment]
Symbols that are in the `main.c` are kept, maybe it's an issue with the libraries that are linked in.

**Comment by yurydelendik** [comment]
Fixed by removing `--strip-debug` option, see https://github.com/wasdk/wasmexplorer-service/commit/56115f46a538c7b901585f5e33475869e7882ebe
