### ISSUE TITLE
Add support for Rust compilation.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#13]

**Comment by haxxorsid** [comment]
I was looking forward to this, since many days. I am lacking time.

**Comment by haxxorsid** [comment]
Good. I was looking forward to this, since many days. But I was lacking time.

**Comment by mbebenita** [comment]
Primitive support landed in https://github.com/mbebenita/WebAssemblyStudio/commit/53f65ed4ea8116d5863a3651532dde6af6ebd11a

**Comment by mbebenita** [comment]
Just to keep track of things, we should also add rustfmt support - https://github.com/wasdk/WebAssemblyStudio/wiki

**Comment by yurydelendik** [comment]
Somewhat addressed. User story for Rust is at #41, so we can close this one.

> Just to keep track of things, we should also add rustfmt support

Tracking that in #144
