### ISSUE TITLE
Upload directories

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/WebAssemblyStudio#131]
See https://github.com/wasdk/WebAssemblyStudio/pull/36#issuecomment-363899987

We need to investigate if it's possible to upload a directory. It will provide alternative to have templates locally and upload them into WebAssembly Studio.

**Comment by yurydelendik** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory

**Comment by haxxorsid** [comment]
It will be helpful if someone first works on #39 and also adds drag, drop functionality.
Then this can work out a bit easier.

**Comment by mbebenita** [comment]
Partially fixed by #154, there's sill some follow up work to be done here, like error checking and dragging and dropping.
