### ISSUE TITLE
Context menu immediately disappears in Firefox.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#15]

**Comment by AnshulMalik** [comment]
Little more info would help here since it's not clear what context menu, and what should be the expected behavior.

**Comment by mbebenita** [comment]
If you go to https://webassembly.studio/?f=tqfv5 using Firefox, and right click on a file in the workspace on the left, you'll notice that the menu immediately disappears as soon as you release the right mouse button. If you hover the cursor over the menu a and release the mouse button there, then it works as expected, but the general case is busted. In Chrome it works as expected.

**Comment by haxxorsid** [comment]
![Blank](https://image.prntscr.com/image/Q3kqTO_9TB6Qt7SZtiwuNQ.png)

Firefox 47

**Comment by mbebenita** [comment]
Is this the latest version of Firefox?

**Comment by haxxorsid** [comment]
Naah Firefox 47.

**Comment by mbebenita** [comment]
Web assembly only works in the latest versions of Firefox, so we don't plan on supporting older versions. That said, we should probably put up a popup saying that the browser version is not supported.

**Comment by haxxorsid** [comment]
Specify affected versions of Firefox.
I tried the Nightly build and Firefox 57. I don't see this problem in those.

**Comment by AnshulMalik** [comment]
I can reproduce it in Firefox 58.0.1
