### ISSUE TITLE
No "Save" command found

### ISSUE THREAD

**Issue by chrisjj** [wasdk/WebAssemblyStudio#153]
How do I save a changed source?

I chose to create an empty C project, got a non-empty C project, made a source change, did Build, and got this warning.

![image](https://user-images.githubusercontent.com/6157073/36938706-7a182bbc-1f1d-11e8-8735-6217ae332635.png)

**Comment by mbebenita** [comment]
`Cmd+S` should work, there used to be a button to do this, but it went missing. I'll look for it.

**Comment by chrisjj** [comment]
Thanks. It works.

**Comment by mbebenita** [comment]
Fixed by https://github.com/wasdk/WebAssemblyStudio/pull/157
