### ISSUE TITLE
Empty (sic) C project Build gives only one empty line in Output

### ISSUE THREAD

**Issue by chrisjj** [wasdk/WebAssemblyStudio#156]
And no indication that the build took place.

Perhaps this line was supposed to be a completion message?

![image](https://user-images.githubusercontent.com/6157073/36938826-54e5d1a8-1f1f-11e8-92f5-59c4d2d4236a.png)

**Comment by mbebenita** [comment]
The only indication at the moment is that a `main.wasm` file is created. Would be great to figure out a better way to give feedback.

**Comment by haxxorsid** [comment]
@mbebenita Reminds me of: [this](https://github.com/wasdk/WebAssemblyStudio/issues/22#issuecomment-366009626)

**Comment by chrisjj** [comment]
Call me old-fashioned :) but how about 

    [info]: Build complete

**Comment by mbebenita** [comment]
That's a good suggestion. However, there are several other actions that users can take, through context menus and such which would need some kind of feedback too. We could write all these to the output window, but we haven't though through all the implications just yet.
