### ISSUE TITLE
Markdown Edit/Preview Mode

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#17]
Currently only preview mode is supported. We need to work out a way to switch between preview/edit modes, and preferably make it possible to open edit / preview files in different tabs.

**Comment by AnshulMalik** [comment]
We can add a footer bar to the editor, where we can place small buttons, which can be used to take certain actions like toggle preview

**Comment by haxxorsid** [comment]
I'm working on this since yesterday. I might be able to figure out properly and put a PR. If not, I will give update here.

**Comment by AnshulMalik** [comment]
Looks awesome @haxxorsid, waiting to see the PR here.

**Comment by haxxorsid** [comment]
Close this.
