### ISSUE TITLE
Wasm fiddle specification of wasmImports?

### ISSUE THREAD

**Issue by jmanden** [wasdk/WebAssemblyStudio#178]
Hi,

I was wondering if anyone could show me what the code is for the wasmImports in the basic https://wasdk.github.io/WasmFiddle/ example?

Kind regards

**Comment by yurydelendik** [comment]
In wasmfiddle, there is "Imports Template" tab that shows JS for specific C code:
<img width="575" alt="screen shot 2018-04-04 at 7 38 50 am" src="https://user-images.githubusercontent.com/1523410/38308040-6c707646-37db-11e8-929b-8dc17dc0fdf2.png">

Closing as answered.
