### ISSUE TITLE
hello_world_c: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]

### ISSUE THREAD

**Issue by kainino0x** [wasdk/WebAssemblyStudio#185]
This warning is shown when the hello_world_c project is built:
```
warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
```

It seems like

https://github.com/wasdk/WebAssemblyStudio/blob/2740c1961d393fecc1029f1a77dcf2ca7ee2d2d9/templates/hello_world_c/src/main.c#L12

should be
```c
extern void putc_js(char c);
```

**Comment by yurydelendik** [comment]
> should be
> extern void putc_js(char c);

Thank you for the fix.
