### ISSUE TITLE
Stacked Toasts

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#19]
We should work out a scheme where more toasts can be fired off and stacked up on top of each other.

**Comment by AnshulMalik** [comment]
Should we use a package for this or build our own?

**Comment by AnshulMalik** [comment]
If we are to use external package, https://github.com/fkhadra/react-toastify is a good candidate

**Comment by haxxorsid** [comment]
People can refer to this: [wasdk/WasmFiddle#11](https://github.com/wasdk/WasmFiddle/pull/11)

**Comment by AnshulMalik** [comment]
Looks awesome @haxxorsid, waiting to see the PR here.

**Comment by mbebenita** [comment]
I've tried this component before, and found it difficult to style. In my experience, rolling our own components that do exactly what we want them to do is easier than depending on another codebase that does almost what we want, and a lot of things we don't.

**Comment by haxxorsid** [comment]
Toasts are using React-Modal. React-modal doesn't allow a single wrapper wrapping multiple modals. And we need a wrapper around all modals to make them stackable. So we will have to remove react-modal and make a pure toast just like [wasdk/WasmFiddle#11](https://github.com/wasdk/WasmFiddle/pull/11)

**Comment by mbebenita** [comment]
I'm open to using a more advanced Toast implementation.

**Comment by haxxorsid** [comment]
This issue can be closed.

**Comment by haxxorsid** [comment]
This issue can be closed.
