### ISSUE TITLE
Mouse wheel click ("open in new tab") on "Github Issues" triggers the popup blocker

### ISSUE THREAD

**Issue by konstin** [wasdk/WebAssemblyStudio#193]
When clicking with the mouse wheel on the "GitHub issues" button in the top left, WebAssembly Studio should open a new tab instead of trying to open a new window, especially since the latter triggers firefox' popup blocker.

**Comment by layderv** [comment]
Adding an `<a href target="_blank">` element (with a style such as `color: inherit`) works properly.
I've tried to pass the event to `onClick` and switch behavior on a middle mouse click, but I haven't managed to make it work yet.
