### ISSUE TITLE
Rust projects should be built before running

### ISSUE THREAD

**Issue by konstin** [wasdk/WebAssemblyStudio#194]
Trying to run a rust program before compiling at least once will (obviously) lead to an error. Running without re-compiling can also lead to very confusing situations where the new javascript runs with the old rust code. I therefore suggest to always build the code before running it. This would also match cargo's behavior.

**Comment by yurydelendik** [comment]
> I therefore suggest to always build the code before running it. 

One of the goals to show users where all files are coming from, trying to hide and automate may contradict this goal. Adding "Build & Run" may be a better choice here.

**Comment by konstin** [comment]
Indeed, that would be a good solution!

**Comment by yurydelendik** [comment]
>  Adding "Build & Run" may be a better choice here.
> Indeed, that would be a good solution!

Closing as fixed.
