### ISSUE TITLE
Type Error: Network Errror when attempting to fetch resource

### ISSUE THREAD

**Issue by grigorijmarkelov** [wasdk/WebAssemblyStudio#196]
Hello.It may be a noob question but when I download example projects (e.g. greeting or console.log) and unpack then it gives me error in dev.console while opening html file in firefox, version 59.When clicking 

> Learn More

 mdn page opens []https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible

It relates with fetch call, surely.But in the past when i tried fetch api mdn examples locally it all worked.
Need advice

**Comment by yurydelendik** [comment]
Please provide exact steps to reproduce the issue and share the complete example.

**Comment by yurydelendik** [comment]
> or now i need to add application/wasm mime type to my localhost on debian

It does not look like it is a valid issue for webassembly.studio -- supporting a web server is out of scope of this project. Closing as such.

Please follow https://github.com/WebAssembly/design/issues/1202 to get more answers.
