### ISSUE TITLE
Support multiple source files for Rust

### ISSUE THREAD

**Issue by tschneidereit** [wasdk/WebAssemblyStudio#212]
It'd be very nice to be able to split Rust projects into multiple files. Right now that's not possible because the compiler invocation is hard-coded to pass in a single source file, but it seems like it shouldn't be hard to change that to use a list of files.

cc @alexcrichton, @yurydelendik

**Comment by ashleygwilliams** [comment]
this works now. closing.

**Comment by pandadelphin** [comment]
Hello @ashleygwilliams, when will this be deployed to https://webassembly.studio. At the moment I receive the following error '[error]: Supporting compilation of a single file, but 3 file(s) found' in console output if I try to compile multiple files.
Here is my build.ts:
```
import * as gulp from "gulp";
import { Service, project } from "@wasm/studio-utils";

gulp.task("build", async () => {
  const options = { lto: true, opt_level: 's', debug: true };
  const fileNames = ["emscripten.rs", "matrix.rs", "main.rs"];
  const files = fileNames.map(fileName => project.getFile("src/webgl/" + fileName));
  const data = await Service.compileFiles(files, "rust", "wasm", options);
  const outWasm = project.newFile("out/main.wasm", "wasm", true);
  outWasm.setData(data["a.wasm"]);
});

gulp.task("default", ["build"], async () => {});
```
