### ISSUE TITLE
Multiple Monaco editor dependencies

### ISSUE THREAD

**Issue by ollelauribostrom** [wasdk/WebAssemblyStudio#220]
There are currently two Monaco Editor dependencies. One is located in lib/monaco-editor and one is listed in package.json. These two are identical when it comes to the versions, so we could try to remove one of them.

In my opinion it would probably be easiest to manage the Monaco Editor dependency if sticking to the one installed from npm. To do this, Webpack must be configured to load the editor as described in ["Integrating the ESM version of the Monaco Editor"](https://github.com/Microsoft/monaco-editor/blob/HEAD/docs/integrate-esm.md).

Any thoughts?

**Comment by yurydelendik** [comment]
@mbebenita mentioned that he did some cosmetic modifications to the files

**Comment by ollelauribostrom** [comment]
I've experimented a bit with this in #221. Looks like it could be doable since the Monaco Editor distributed at npm now includes the components TreeView, ContextMenuService, ContextViewService, TreeDefaults and Action that are used in monaco-utils.ts.

**Comment by mbebenita** [comment]
Great, then it's definitely the right way to go.

**Comment by yurydelendik** [comment]
Closed by #221
