### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/WebAssemblyStudio#27]
Currently we a choosing to set the project license to generic MIT open source license. See #25

@mbebenita is asking if "everyone that’s contributed ... to reply with `I Agree` to the license change?"

/cc @haxxorsid @nileshgulia1 @AnshulMalik @tschneidereit

Thank you.

**Comment by yurydelendik** [comment]
I Agree

**Comment by mbebenita** [comment]
I Agree

**Comment by tschneidereit** [comment]
I Agree

**Comment by AnshulMalik** [comment]
I Agree

**Comment by nileshgulia1** [comment]
I agree

**Comment by haxxorsid** [comment]
I agree

**Comment by AnshulMalik** [comment]
Won't a license file in root directory do the work? We are adding the license text to every file

**Comment by nileshgulia1** [comment]
Yes, we can add license in the root,why we are adding in every file? @yurydelendik  @mbebenita

**Comment by yurydelendik** [comment]
> We are adding the license text to every file

There are many file from different projects and every project has different license. We need to be specific about files we are creating.

**Comment by yurydelendik** [comment]
Closing the issue as resolved
