### ISSUE TITLE
Integrate functionality from WasmCodeExplorer

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#34]
Currently, the only way to inspect a wasm file is to see its disassembled output. It would be great if we could also let users look at the binary file directly: https://wasdk.github.io/wasmcodeexplorer/

**Comment by haxxorsid** [comment]
I think normally this will slow down the client's browser, maybe crash or lag if he tries to inspect. Later, we will have to make sure all the data gets cleaned up when the client exits the option.

**Comment by mbebenita** [comment]
One temporary fix would be to open WasmCodeExplorer in an pop window and pass the `.wasm` file to it.

**Comment by yurydelendik** [comment]
See also #32
