### ISSUE TITLE
Add Beta Badge

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#35]
The project website has been shared more broadly and users may be disappointed wen they encounter bugs, we should make the site as beta and also put a link to this repo so issues can be filed.

**Comment by nileshgulia1** [comment]
That's a great idea :) How about a `BETA` ribbon like on top-right.

**Comment by haxxorsid** [comment]
Beta badge(Source: codepen):
[Badge][https://image.prntscr.com/image/7XTY34OjSiKXx3WN1k1VAA.jpg]
Issues button can be added to the foot/topbar in a attractive/noticeable decent way:
[Issues][https://image.prntscr.com/image/HmcqsPXqT1yYH86o9DnidA.jpg]

**Comment by haxxorsid** [comment]
Beta badge(Source: codepen):
![Badge](https://image.prntscr.com/image/7XTY34OjSiKXx3WN1k1VAA.jpg)

Issues button can be added to the foot/topbar in a attractive/noticeable decent way:
![Issues](https://image.prntscr.com/image/HmcqsPXqT1yYH86o9DnidA.jpg)

**Comment by mbebenita** [comment]
I like it. I prefer the Issues at the top, and maybe we can call this "GitHub Issues" so users know the will be going to GitHub.

**Comment by mbebenita** [comment]
Fixed by #37
