### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by LiberTang0** [wasdk/WebAssemblyStudio#359]
Python 3 support

**Comment by yurydelendik** [comment]
Can you clarify how it will be useful? Personally, I don't see how it can fit in the project [vision](https://github.com/wasdk/WebAssemblyStudio/wiki#vision).

**Comment by LiberTang0** [comment]
The vision:
Learn & Teach: Python is one of the most used languages to learn and teach programming (MIT, Stanford..etc.)

Work & Play: Python is one the most used language for web development (Django/Flask/Odoo)

And I think that Python will drive user adoption of WebAssemblyStudio.

**Comment by yurydelendik** [comment]
> And I think that Python will drive user adoption of WebAssemblyStudio.

WebAssembly Studio is created with purpose of adopting WebAssembly and not other way around. Evolving WebAssembly Studio as a product is not a primary goal here. We may consider adding compiled to WebAssembly Python library, just to study interoperability between JS/Wasm/Python.

Closing as out of scope. You are welcome to fork the project and tweak the vision towards Python driving adoption of WebAssemblyStudio (? but I recommend to change name here). Thanks.
