### ISSUE TITLE
Fails to warn about malformed WAT

### ISSUE THREAD

**Issue by blackhole12** [wasdk/WebAssemblyStudio#360]
While I was testing my own webassembly compiler against the [official interpreter tests](https://github.com/WebAssembly/spec/tree/b3de271e8da3f8aa29a9ea3455665f88b1a4c3d2/test/core), I was trying to verify the results against webassembly.studio, but accidentally discovered that the compiler fails part of `call_indirect.wast`. Namely, it is not verifying that the inline type declarations match the explicit type reference. Instead, the inline type declarations _override the explicit type reference_, which is very unexpected.

This `.wat` file currently compiles in webassembly.studio:
```wasm
(module
    (type $sig (func (param i32) (result i32)))
    (table 0 anyfunc)
    (func (result i32)
      (call_indirect (type $sig) (result i32) (i32.const 0))
    )
)
```

This code is malformed, because there exists an inline type declaration in addition to the explicit type reference. The inline type declaration forms a function that takes no parameters and returns `i32`. The referenced type, however, is a function that takes `i32` and returns `i32`. This is expected to throw an "inline function type" error in [`call_indirect.wast`](https://github.com/WebAssembly/spec/blob/b3de271e8da3f8aa29a9ea3455665f88b1a4c3d2/test/core/call_indirect.wast#L359).

Instead, Webassembly.studio discards the referenced type and uses the inline type to compile the function. If the situation is reversed, the code does not compile, but only because the type is now expecting a parameter that is not provided, not because of a type mismatch.

```wasm
(module
    (type $sig (func (result i32)))
    (table 0 anyfunc)
    (func (result i32)
      (call_indirect (type $sig) (param i32) (result i32) (i32.const 0))
    )
)
```

I'm not actually sure if the webassembly compiler is part of webassembly.studio or is maintained separately. If the compiler being used by webassembly.studio has it's own repo, I can refile the bug there, since this is strictly a compiler issue.

**Comment by MaxGraey** [comment]
You should address this issue to [`wabt` project](https://github.com/WebAssembly/wabt).

**Comment by blackhole12** [comment]
Closing and moving to appropriate project
