### ISSUE TITLE
Can't compile or execute the AssemblyScript example project

### ISSUE THREAD

**Issue by andys8** [wasdk/WebAssemblyStudio#371]
I'm documenting my experience as a novice to the project. Could be a simple mistake, or that the project is not supported, or something else leads to a dependency not being loaded.

#### Issue

Opening <https://webassembly.studio> and creating a new `AssemblyScript` project will lead to an error in the console.

![image](https://user-images.githubusercontent.com/13085980/46342754-dd1f8280-c63b-11e8-9474-bf70dbb960e9.png)

Opening `main.ts` marks the syntax as invalid.
![image](https://user-images.githubusercontent.com/13085980/46342789-f58f9d00-c63b-11e8-9c07-889317c1d23d.png)

Build fails with 
![image](https://user-images.githubusercontent.com/13085980/46342812-06401300-c63c-11e8-99f8-2cd13e5f4d3e.png)

#### System

Chrome: Version 69.0.3497.100 (Official Build) (64-bit), Adblocker disabled
OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.10.0-42-generic

**Comment by iFlameing** [comment]
@andys8  I  also open the webassembly studio and create empty assembly project but I don't get any error can you explain what you are doing  or how I reproduce this issue in my machine.

**Comment by mindplay-dk** [comment]
I'm seeing a different error - related? Looks like it can't find the file at all:

```
ERROR: Entry file 'main.ts' not found.
    at exports.main (https://cdn.jsdelivr.net/gh/AssemblyScript/assemblyscript/dist/asc.js:1:361155)
    at Object.asc.main.main (eval at d (https://webassembly.studio/dist/main.bundle.js:1:32474), <anonymous>:20:12)
    at r.gulp.task.callback [as promiseMaker] (eval at gulp (https://webassembly.studio/dist/main.bundle.js:1:34094), <anonymous>:7:7)
    at o.makePromise (https://webassembly.studio/dist/main.bundle.js:1:31659)
    at s.runInstance (https://webassembly.studio/dist/main.bundle.js:1:31955)
```

**Comment by MaxGraey** [comment]
@mindplay-dk waiting PR which fixed this:
https://github.com/wasdk/WebAssemblyStudio/pull/396
