### ISSUE TITLE
clarify maintenance status of this project

### ISSUE THREAD

**Issue by ashleygwilliams** [wasdk/WebAssemblyStudio#381]
cc @tschneidereit @yurydelendik we should make it clear that this project is not actively maintained. i have some ideas but was curious to see what ya'll think first.

**Comment by yurydelendik** [comment]
We cannot say we actively maintaining project, though "maintained | seldom" label will be a good reflection of what is going on.

**Comment by carlsmith** [comment]
@yurydelendik - Do you know if the devs can still accept PRs?

The WAT tools are especially dated, using an obsolete version of the language (#434 etc).

**Comment by yurydelendik** [comment]
> Do you know if the devs can still accept PRs?

Yeah, sorry, support somewhat stale for this project. I'm scanning for quality PRs, and those that are in useful and in good state, I'm merging.

> using an obsolete version of the language (#434 etc).

Unfortunately this one might require more than the frontend update, e.g. service update (I did not look at it)

**Comment by carlsmith** [comment]
Thanks for the update.
