### ISSUE TITLE
Decompiling AssemblyScript

### ISSUE THREAD

**Issue by willemneal** [wasdk/WebAssemblyStudio#392]
I've been working on the [AssemblyScript decompiler](https://github.com/AssemblyScript/assemblyscript/pull/346) and was wondering how hard it would be to add an option when disassembling the WebAssembly binary.  It's not nearly camera ready, but just thought I'd reach out now.

**Comment by yurydelendik** [comment]
Sounds like a awesome idea. It is out of scope of this project though, and I don't think it will make sense to track this in the WebAssembly studio repo yet. Once the decompiler will be released, you can follow up with the integration PR. 

cc @dcodeIO

**Comment by willemneal** [comment]
Thanks for the reply!  I’ll return when it’s released.
