### ISSUE TITLE
where is the code for the compiler services?

### ISSUE THREAD

**Issue by dominictarr** [wasdk/WebAssemblyStudio#394]
I've been trying to compile simple C programs to wasm. most of the instructions I'm finding recommend `emcc` which creates a hell of a lot of boilerplate, that I'd rather not have. I've recently been writing web assembly text format by hand, because I want to really understand how it works, and I was pleased to see that WA studio generates simple wasm, that aside from a couple of extra lines, I would have written by hand.

However, I'd like to know how to set up clang to do this though - I was gonna look at the code in WA studio - but it seems that they rely on server side code have not been open sourced? is this correct? or if there is some better resource than the ones I have been finding that would be most appreciated.

**Comment by yurydelendik** [comment]
> but it seems that they rely on server side code have not been open sourced? 

See https://github.com/wasdk/WebAssemblyStudio/wiki/Micro-services

Closing as answered.

**Comment by dominictarr** [comment]
thank you @yurydelendik !
