### ISSUE TITLE
Corrupted base64 encoding

### ISSUE THREAD

**Issue by jeff1010322** [wasdk/WebAssemblyStudio#400]
The padding for base64 encoding is adding one too many equal signs when the byte remainder is 1.  

https://github.com/wasdk/WebAssemblyStudio/blob/fbf7d4ef5e09b2798caf5137081ff21bcd184aa1/src/util.ts#L135

This is based on a gist that correctly appends 2 equal signs:

https://gist.github.com/jonleighton/958841#file-base64arraybuffer-js-L53

**Comment by yurydelendik** [comment]
Closed by #401
