### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by MaxGraey** [wasdk/WebAssemblyStudio#403]
It seems SSL certificate or domain expired

**Comment by Galaxtone** [comment]
Are there any mirror sites to use for the time being? (or even directly accessing the official site using an IP address)

**Comment by yurydelendik** [comment]
New SSL certificate shall be up.

**Comment by MaxGraey** [comment]
Thanks!

**Comment by Galaxtone** [comment]
Thank you, kind bearded man.
