### ISSUE TITLE
CORS issue on main site

### ISSUE THREAD

**Issue by richardanaya** [wasdk/WebAssemblyStudio#405]
Affects Chrome OS, Chromium on Linux

![screenshot 2019-01-29 at 2 41 13 pm](https://user-images.githubusercontent.com/294042/51945599-0676d200-23d4-11e9-9bd8-f91cfbf6c0ad.png)

**Comment by MaxGraey** [comment]
Should be fix for now

**Comment by yurydelendik** [comment]
Fixed by 0821d78
