### ISSUE TITLE
AssemblyScript default project can not be build

### ISSUE THREAD

**Issue by d-bardiau** [wasdk/WebAssemblyStudio#418]
If a new empty AssemblyScript project is created any attempt to build the project will fail: 

[info]: Task build is running...
[error]: Task build failed: Module name "assemblyscript/bin/asc" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded

**Comment by MaxGraey** [comment]
It's known issue. It will be repaired automatically from your side soon. Sorry for the inconvenience

**Comment by d-bardiau** [comment]
Thank you for you answer. I'm looking forward to using WebAssembly Studio with AssemblyScript again.

**Comment by sffc** [comment]
AssemblyScript compile is still broken with this error

**Comment by MaxGraey** [comment]
This should be fixed in this PR https://github.com/wasdk/WebAssemblyStudio/pull/436

**Comment by munrocket** [comment]
Can we use this [demo](https://github.com/pedrouid/assemblyscript-demo) as an example?
