### ISSUE TITLE
Beta banner covers View Workspace button.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#42]
![image](https://user-images.githubusercontent.com/311082/35955128-5570c3c0-0c42-11e8-8a1d-a3d35036dfc6.png)

![image](https://user-images.githubusercontent.com/311082/35955136-6195fab2-0c42-11e8-9596-74a66a0ee79d.png)

**Comment by mbebenita** [comment]
A result of #37

**Comment by nileshgulia1** [comment]
@mbebenita  How about putting BETA banner on top-right?
![screenshot from 2018-02-08 12-23-00](https://user-images.githubusercontent.com/22280901/35959276-e6ecef6c-0cca-11e8-9211-8ef6ff9780ff.png)

**Comment by haxxorsid** [comment]
[Commit](https://github.com/wasdk/WebAssemblyStudio/pull/44)

Close this.
