### ISSUE TITLE
Compile C,C++, Rust client-side

### ISSUE THREAD

**Issue by lastmjs** [wasdk/WebAssemblyStudio#422]
Hopefully it's obvious why this would be amazing. I would love to see self-hosted versions of the compiler toolchains. Having Wasm versions of the toolchains would make them much easier to use, as they'd work with no extra setup in the browser, in Node, and anywhere else there is a Wasm virtual machine. I see some work on this is planned here: https://github.com/wasdk/WebAssemblyStudio/projects/3#card-7303443

My main questions are what is required to get this to work? What exactly needs to be compiled to Wasm? Which projects exactly? I'm most interested in the Rust toolchain for now. Has anyone compiled rustc to Wasm yet? What's the status on all of this?

**Comment by yurydelendik** [comment]
> My main questions are what is required to get this to work?

Related subset of llvm-project to be compiled to webassembly: clang, lld, etc.

> What exactly needs to be compiled to Wasm? Which projects exactly?

clang and its dependencies (see wasi-sdk) and rustc

> I'm most interested in the Rust toolchain for now. Has anyone compiled rustc to Wasm yet? What's the status on all of this?

Nobody on our side evaluated this yet. 

Closing as answered. (The people who has status updates may append comments)
