### ISSUE TITLE
wasm file compiled from c++ is wrong

### ISSUE THREAD

**Issue by stkevintan** [wasdk/WebAssemblyStudio#428]
https://webassembly.studio/?f=yt0jt76eey

**Comment by MaxGraey** [comment]
You should use `WASM_EXPORT`
```c
#define WASM_EXPORT __attribute__((visibility("default")))

WASM_EXPORT void sort() {
...
}
```

**Comment by stkevintan** [comment]
@MaxGraey Thank you!

**Comment by GirkovArpa** [comment]
Why can't we use `extern "C" { ... }` like @ [the original website](https://wasdk.github.io/WasmFiddle//)?

Seriously, the original website is 100x better.  It lets me write C++ and "just works".
