### ISSUE TITLE
Verify if browser supports WebAssembly

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/WebAssemblyStudio#46]
When WebAssemblyStudio is opened in the browser that does not support WebAssembly v1, we need to show a warning message that will inform that the application will not function normally/as expected.

**Comment by nileshgulia1** [comment]
@yurydelendik  should we only check that webAssembly is present in browser as a object ? I'm thinking of something like this:
``` javascript 
 try {
        if (typeof WebAssembly === "object"
            && typeof WebAssembly.instantiate === "function") {
            const module = new WebAssembly.Module(Uint8Array.of(0x0, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00));
            if (module instanceof WebAssembly.Module)
                return new WebAssembly.Instance(module) instanceof WebAssembly.Instance;
```

**Comment by yurydelendik** [comment]
It's too heavy to start invoking WebAssembly.Module. Just `typeof WebAssembly === "object"` and some check that indicates v1 will work fine.

**Comment by mbebenita** [comment]
I would recommend doing this check in `index.tsx` to avoid any unnecessary loading and using a `ReactModal` component as a prompt.

**Comment by nileshgulia1** [comment]
@mbebenita  changes are not reflecting into the DOM when I change some file, why's this happening?

**Comment by mbebenita** [comment]
@nileshgulia1 can you elaborate please?

**Comment by mbebenita** [comment]
Sorry, accidentally closed the issue.

**Comment by nileshgulia1** [comment]
@mbebenita  When I use to change some UI related code ,same should reflect onto the DOM(webpage) for eg: If I  change the header from `Web Assembly Studio` to some other name , its not actually changing in DOM or webpage. It suddenly happened, as It was working nicely before.

**Comment by mbebenita** [comment]
Fixed by https://github.com/wasdk/WebAssemblyStudio/pull/120
