### ISSUE TITLE
Design a more compact layout for small viewports.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#59]
When embedding in Medium, the default width of the embedding is quite small which leads our buttons to get all bunched up and overflow onto the next line. We should figure out a way to:

1. Hide or move the GitHub Issues button out of the way.
2. Reduce or hide button labels so thing fit.
3. Any other ideas?

![image](https://user-images.githubusercontent.com/311082/36065401-0104a450-0e4f-11e8-978c-6750be15d674.png)

**Comment by haxxorsid** [comment]
Slide/scroll buttons horizontally.
Like, grab a button drag it on right then the hidden left side button will come forth.
Example: We have tabs in Android like the one in Play Store- 
![Android tabs](https://i.snag.gy/xWSwaX.jpg)

**Comment by mbebenita** [comment]
At 640 width, this now looks like:

![image](https://user-images.githubusercontent.com/311082/36460420-145e19de-166d-11e8-9c59-d76f0d848bef.png)
