### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by AwesomeObserver** [wasdk/WebAssemblyStudio#61]
**After build, Rust project not running.**

![screenshot_1](https://user-images.githubusercontent.com/19798308/36066895-e41afcde-0ec3-11e8-9df4-0ca2385bb589.png)

_main.js file_
```js
fetch(getFileURL('out/main.wasm')).then(response =>
  response.arrayBuffer()
).then(bytes => WebAssembly.instantiate(bytes)).then(results => {
  instance = results.instance;
  document.getElementById("container").innerText = instance.exports.add_one(41); //Error
});
```
**Error:** Uncaught (in promise) TypeError: instance.exports.add_one is not a function.

_main.rs file_
```Rust
fn main() {
    println!("Test");
}
```

**Comment by yurydelendik** [comment]
That's correct behavior -- 'main.js' calls non-existent in the 'main.rs' exported function.

**Comment by mbebenita** [comment]
@AwesomeObserver just as a tip, when filing an issue you can click fork and paste the URL to the fiddle so we can see exactly what you see. This would also let us test out the fiddle functionality.

**Comment by yurydelendik** [comment]
Closing issue as answered. The "expected behavior" clause is missing, so it's hard to tell how the issue shall be resolved.
