### ISSUE TITLE
Clean up icon handling.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#65]
File icons in the File Tree are from `seti.woff` and defined in `theme.css`. Icons in tabs are loaded from the `svg/` directory, other icons are defined in `Icons.tsx`, and others are defined in `octicons` so it's a bit of a mess.

**Comment by yurydelendik** [comment]
The issues does not specify expected behavior. Looks #126 addressed the main concern though. Closing as fixed.
