### ISSUE TITLE
Deleting a file that is opened in a tab doesn't close the tab.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#66]
Tabs should not hang on to deleted files.

**Comment by hleal18** [comment]
Hello, I'm getting familiar to the project and I'd like to know if there's someone working on this bug already, otherwise I'd like to give it a try and work on it.

**Comment by mbebenita** [comment]
I don't think anyone is working this at the moment, feel free to give it a shot.

**Comment by yurydelendik** [comment]
Fixed by #161
