### ISSUE TITLE
Add a Save button.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#71]
At the moment, we rely on keyboard shortcuts to save file buffers, which is a problem for mobile devices. Once possible place to add such a button is next to the split pane button.

![image](https://user-images.githubusercontent.com/311082/36124770-3f41dcca-1006-11e8-93b1-32810eeceef6.png)

The button can be disabled when there's nothing to be saved.

**Comment by Biboswan** [comment]
Hi, I would like to work on this.

**Comment by mbebenita** [comment]
That would be great. Are you able to assign yourself to the issue?

**Comment by Biboswan** [comment]
Do you mean self-assign ? I don't think there is such permissible option.

**Comment by yurydelendik** [comment]
@Biboswan  comment "I would like to work on this" is okay to start work, but normally you don't need to ask permission to work on something. Just make sure, when you are submitting a PR, to refer this issue in the "Associated issue:" field.

**Comment by mbebenita** [comment]
@Biboswan but I do think it's a good idea to say you're interested in an issue, in case others may be working on the same thing.

**Comment by haxxorsid** [comment]
Close this
