### ISSUE TITLE
Control Center Collapse Button doesn't work yet.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#80]
![image](https://user-images.githubusercontent.com/311082/36170143-5fb317a0-10b3-11e8-8218-03e132b24bcd.png)

This should work pretty much like the button that collapses the workspace.

**Comment by RMCoder198** [comment]
I want to hide the output and problems area along with output screen after hitting that button. So, that user can see more code without scrolling.
@mbebenita 
Should i work on this in my way ?

**Comment by RMCoder198** [comment]
Yes ,ok.

**Comment by mbebenita** [comment]
Fixed by https://github.com/wasdk/WebAssemblyStudio/pull/120
