### ISSUE TITLE
WebAssembly Studio or is it Web Assembly Studio?

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#81]
Space or no space?

**Comment by mbebenita** [comment]
I think it should be WebAssembly Studio, with no space.

**Comment by yurydelendik** [comment]
(Votes for Web Assembly Studio go here)

**Comment by mbebenita** [comment]
K, it looks like we have a winner. Fixed by https://github.com/wasdk/WebAssemblyStudio/commit/520d7077b51f1679d8e318f8aeaa5225023a9f45
