### ISSUE TITLE
DirectoryTree is not changing on resize

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/WebAssemblyStudio#92]
STR:
1. open not-tall  (~200px in height) browser window
2. navigate to https://http://webassembly.studio/
3. increase height on the window
4. create a project from a template
5. scroll directory tree up and down

Notice that the tree is not extended all the way to the bottom.

It's expected that tree on the left takes all available space.

![2018-02-15 08 42 32](https://user-images.githubusercontent.com/1523410/36262368-d430cac6-122c-11e8-96f2-c70640a32366.gif)

**Comment by haxxorsid** [comment]
[#96](https://github.com/wasdk/WebAssemblyStudio/pull/96)
Close.

**Comment by haxxorsid** [comment]
Issue has been solved. Close this.
