### ISSUE TITLE
Fix Toast Style

### ISSUE THREAD

**Issue by mbebenita** [wasdk/WebAssemblyStudio#98]
Font Face doesn't match the rest of the UI.

![image](https://user-images.githubusercontent.com/311082/36289823-074b274a-1277-11e8-9e8f-96789f96b450.png)

**Comment by thuselem** [comment]
Should this match the font used in the toolbar?

![toolbar](https://user-images.githubusercontent.com/7957636/36298832-f71af1ce-12ae-11e8-8d1f-95ae62cc710d.png)

**Comment by haxxorsid** [comment]
Merged: #102 
Close this.

**Comment by haxxorsid** [comment]
Close this

**Comment by haxxorsid** [comment]
Close this
