### ISSUE TITLE
Just-opened files are all-selected occasionally

### ISSUE THREAD

**Issue by dcodeIO** [wasdk/WebAssemblyStudio#99]
![select](https://user-images.githubusercontent.com/1136893/36300227-ad9a250e-1300-11e8-9b8c-aadc8d3dfbad.jpg)

Unfortunately, I haven't yet figured out a reliable way to trigger this, but this happens rather regulary on my end when switching between files. Did someone else notice this or is it my PC? :)

**Comment by haxxorsid** [comment]
Not me.

**Comment by yurydelendik** [comment]
@dcodeIO what do you use for switching between files? with exact steps, including e.g. "click shift key + holding middle mouse button".

**Comment by dcodeIO** [comment]
I think I found out how to reproduce it:

* Create a new project
* Close all files
* Left-click the empty editor area once (where the file contents would be otherwise)
* Open a file using the directory tree

**Comment by haxxorsid** [comment]
Step 3: Double left clicking the empty editor area reproduces it.

**Comment by mbebenita** [comment]
Is this happening in both Firefox and Chrome?

**Comment by dcodeIO** [comment]
Seems that in Firefox, a single left click is sufficient to trigger this, while in Chrome, a double left click is required.

**Comment by hleal18** [comment]
I want to know if there is someone working on this issue, otherwise, I'd like to work on it.

**Comment by haxxorsid** [comment]
@hleal18 nope I think. You're welcomed to work on this.

**Comment by yurydelendik** [comment]
Fixed by #179
